### PR TITLE
Adding hot starting

### PR DESCRIPTION
**Pull request by lcgraham**
This should take care of issue #128

### CODE REVIEW

**Comment by smattis** [comment]
Are all of the changes in the tests just spacing? I want to make sure we don't lose backward compatibility and not realize it because tests are changed.

**Comment by smattis** [comment]
In the future, can we do changes like formatting whitespace in a separate pull request than substantive code changes? It make it really hard to see what the real changes are.

**Comment by lcgraham** [comment]
I am looking into this now. I agree heartily about preserving backward
compatibility. Also I will make sure to do formatting changes in a separate
pull request from substantive code changes to improve code review. Sorry
about the confusion. I'll have an answer for you shortly on the changes in
the tests.

On Tue, Dec 1, 2015 at 5:05 PM Steven Mattis <notifications@github.com>
wrote:

> In the future, can we do changes like formatting whitespace in a separate
> pull request than substantive code changes? It make it really hard to see
> what the real changes are.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/pull/150#issuecomment-161110122>.
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by lcgraham** [comment]
Many of the formatting changes where to update documentation and fix Sphinx
errors. In the future I will make formatting and documentation updates a
separate pull request.

On Tue, Dec 1, 2015 at 6:15 PM lcgraham <lichgraham@gmail.com> wrote:

> I am looking into this now. I agree heartily about preserving backward
> compatibility. Also I will make sure to do formatting changes in a separate
> pull request from substantive code changes to improve code review. Sorry
> about the confusion. I'll have an answer for you shortly on the changes in
> the tests.
>
> On Tue, Dec 1, 2015 at 5:05 PM Steven Mattis <notifications@github.com>
> wrote:
>
>> In the future, can we do changes like formatting whitespace in a separate
>> pull request than substantive code changes? It make it really hard to see
>> what the real changes are.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UT-CHG/BET/pull/150#issuecomment-161110122>.
>>
> --
>
> Lindley Graham, Ph.D. 2015
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by smattis** [comment]
Cool.

**Comment by lcgraham** [comment]
Note that additional tests have been added for hot starting. Documentation
needs to be updated.


On Tue, Dec 1, 2015 at 6:16 PM lcgraham <lichgraham@gmail.com> wrote:

> Many of the formatting changes where to update documentation and fix
> Sphinx errors. In the future I will make formatting and documentation
> updates a separate pull request.
>
> On Tue, Dec 1, 2015 at 6:15 PM lcgraham <lichgraham@gmail.com> wrote:
>
>> I am looking into this now. I agree heartily about preserving backward
>> compatibility. Also I will make sure to do formatting changes in a separate
>> pull request from substantive code changes to improve code review. Sorry
>> about the confusion. I'll have an answer for you shortly on the changes in
>> the tests.
>>
>> On Tue, Dec 1, 2015 at 5:05 PM Steven Mattis <notifications@github.com>
>> wrote:
>>
>>> In the future, can we do changes like formatting whitespace in a
>>> separate pull request than substantive code changes? It make it really hard
>>> to see what the real changes are.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/UT-CHG/BET/pull/150#issuecomment-161110122>.
>>>
>> --
>>
>> Lindley Graham, Ph.D. 2015
>>
> --
>
> Lindley Graham, Ph.D. 2015
>
-- 

Lindley Graham, Ph.D. 2015

**Pull request merged**
