### PR TITLE
Regular sampling now defines uniform cells

### PR DESCRIPTION
**Pull request by eecsu**
Before it took an interior grid of points from a regular grid of samples that included the boundary. The points are still interior, but now the implicitly defined grid is of uniformly sized rectangles, which is more likely what a user would want anyway.

### CODE REVIEW

**Comment by smattis** [comment]
Actually, if you are going to do this, you should utilize the new method `bet.sample.cartesian_sample_set`. Using that, you never have to form and query the kdtree which is expensive in high dimensions.

**Comment by smattis** [comment]
Also, please make sure the tests pass before doing a pull request.

**Comment by eecsu** [comment]
I am fixing the tests now.

**Comment by eecsu** [comment]
I do not think I want to use the `bet.sample.cartesian_sample_set`. I still want the samples, I just want them to implicitly define such a set of boxes. 

I am glad you pointed out these new methods within the sample set because it looks like they could be used to define certain types of events taken as inputs to the suggested postTools method for computing probabilities of different events described in issue #241. Samples + distances (with a specified metric) would of course be more flexible, but in many cases, I imagine the rectangular or ball sample sets being sufficient.

**Comment by eecsu** [comment]
I think I see what you meant by the cartesian sample set. I was looking at the rectangular sample set method since it inherited from there and it looked like it was just defining lower-left and upper-right corners of boxes (I see the values are actually set as the mid-points now). 

So, if I am interpreting your suggestion correctly, you think I should call this within the regular sampler method of `basicSampling` to generate the sample set of this class as I describe below. 

First, just to clarify, it looks like I would have to drop off the last sample which is always ``[inf, inf]``to avoid inputting that into the model that the sampler is linked to. 

Then, since the use of ``np.meshgrid`` in the cartesian sample set method looks equivalent to what was done in the regular sampler, I could just set up the regular sampler method to call th cartesian sample set method and then remove the last sample value that is returned. This is what you meant, yes?

Also, just to clarify, there is still a need to determine the kdtree on the data space no matter how regular the inputs are (unless the QoI map is globally linear). Where would I be using the kdtree on the input space unless I was using emulated points (which I would not with a regular grid of samples). Or, am I missing something again?

**Comment by smattis** [comment]
Yes, we are just defining the lower-left and upper-right corners of boxes, similar to what is happening here: http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.spatial.Rectangle.html
This is nice (especially in high dimensions) because doing `query` does not require searching a kdtree. It is just checking intervals. Also, the volumes are exact and cheap to compute. 

Yes, the last sample is any part of the domain that is not in the grid, so you don't want to try to run the model for that. I think it is important that it is there, for when we're using calculateP, because otherwise `query` might return an error. 

Yes, there is still a need to determine the kdtree on the data space no matter what.

**Comment by smattis** [comment]
Ok. I do understand more that there will be an issue mapping the "remainder" of the parameter domain to the data domain, since we are using kdtrees in the data domain. I could make a version of cartesian_sample_set, where the cells on the exterior are unbounded in the exterior direction. That would probably be better from defining input sample sets.

**Comment by eecsu** [comment]
Ok. I am inclined to leave the regular sampler as-is for now (your comment literally showed up as I was writing this). There are a few concerns I have about using this in the regular sampler method. One of my main ones is that we may start with a sparse set of regular samples before doing adaptive sampling, but appending is not possible with this class, so I prefer to keep it of the more general type as currently coded in the regular sampler.

Are you okay with that?

**Comment by smattis** [comment]
Yes, this is good for now. It definitely doesn't make sense to use `rectangle_sample_set` or `cartesian_sample_set` or `ball_sample_set` to define input sample sets when you are going to do any adaptive sampling. My main motivation for creating them was for defining probability sample sets in high dimension without the need for using kdtrees. This will appear soon.

For just doing basic sampling on a Cartesian grid, this might be something we want to add down the road. Agree?

**Comment by eecsu** [comment]
I agree.

Also, I totally agree with your motivation. I think this is very much connected to the issue #241 that I mentioned earlier. I see what you did as a great first step towards making some awesome postprocessing tools. I am very excited about it.

**Comment by smattis** [comment]
It looks fine to me, but I want to get an ok from @lcgraham before merging since he wrote most of the sampling methods.

**Comment by eecsu** [comment]
Sounds good. We'll wait for @lcgraham to chime in.

**Pull request merged**
