### PR TITLE
fixed linear/nonlinear examples and myModel in linear.

### PR DESCRIPTION
**Pull request by mpilosov**
Addressing issue #221 by fixing linear and nonlinear uniform sampling examples to conform to new structure of basicSampling. Also modified myModel in linear example folder to address what appears to have been a typo.

### CODE REVIEW

**Comment by lcgraham** [comment]
This is much better. 

With regard to whitespace you might want to check out https://help.github.com/articles/dealing-with-line-endings/ and https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace.

You can also[ close issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/) which is pretty snazzy.

**Comment by eecsu** [comment]
Thanks for catching the typo. Copy/pasted from old file where we called the QoI samples `data`.

I will fix the other examples to use this new basicSampling structure. I did not realize that changed since the beta release.

**Comment by mpilosov** [comment]
I haven't gone through all the examples but many do work and I've been lulled into a false sense of security so many times this past week only to have it undermined. Lost a lot of time to that kind of thing, but hey look! I made my first contribution! A fresh re-fork really helped.

Best
MP

Not sent from my computer.

On Jun 20, 2016, at 09:58, Troy Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for catching the typo. Copy/pasted from old file where we called the QoI samples data.

I will fix the other examples to use this new basicSampling structure. I did not realize that changed since the beta release.

-

**Comment by lcgraham** [comment]
Having a fresh eye on the code is very helpful. Thanks.

**Pull request merged**
