### PR TITLE
Updated emulate_iid_lebesgue, plotting, and new validation example

### PR DESCRIPTION
**Pull request by eecsu**
We discussed the change to emulate_iid_lebesgue.

The plotting changes involve making sure that the range of marginals has a minimum of 0 otherwise the minimum may be set higher and certain features are "washed out" by the scaling. This is very evident in the validation example. Plots in other examples appear unchanged due to localized support of probabilities which made 0 the minimum in most cases. 

The validation example gives the user a chance to explore certain resolution issues by having more control over how the output distribution is discretized in a very explicit way compared to other examples.

### CODE REVIEW

**Comment by lcgraham** [comment]
Can you merge the current state of the master branch into your fork and push that to your fork?

**Comment by eecsu** [comment]
That fix it? I merged right before I made the edits but forgot to merge
again before the last commit and push.

**Comment by lcgraham** [comment]
That did it. Now shippable is running tests as soon as they all pass I'll
merge it.

**Comment by lcgraham** [comment]
4 tests have failed and need to be updated to match the new definition of ``num_l_emulate`` before this can be merged. @smattis since 3 of the failed tests require changes to the manufactured solution in test_calculateP.py can you update them? Thank you.

**Pull request merged**
