### PR TITLE
V2 master update travis

### PR DESCRIPTION
**Pull request by smattis**
Updates the .travis.yml file to build faster and stop stalling. Switch to travis instead of shippable.

### CODE REVIEW

**Comment by lcgraham** [comment]
The latest failure is in sampling which is fixed on my open pull request #184. Do you (@smattis) want me to go ahead and merge that? So that you can pull it into this request?

**Comment by smattis** [comment]
I am liking travis alot more than shippable. Why don't we merge this pull request since it really isn't changing much? Then merge your pull request with it and let the tests run and then I'll merge it. Make sense?

**Comment by smattis** [comment]
@lcgraham This fixes the issues we've been having with CI failing randomly so it would be nice to have it merged before #184

**Comment by smattis** [comment]
@lcgraham I would like to see #184 pass the tests in parallel and with no mpi4py before I merge it. If I don't hear from you, I'm just going to merge it in a few minutes.

**Comment by lcgraham** [comment]
i'm on the phone with troy atm

**Pull request merged**
