### PR TITLE
version-lock scipy

### PR DESCRIPTION
**Pull request by mathematicalmichael**
addresses #335 until we can figure out what in the [1.3.0 Release Notes](https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html) that is causing `adaptiveSampling` to fail.

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
damn... this didn't work because the Travis file uses pip to install scipy, not the `setup.py` file...

**Comment by mathematicalmichael** [comment]
hmmmm. 3.6 passed after the second commit, but 3.7 stalled and exited. never seen that before. trying to restart that last build.

**Comment by mathematicalmichael** [comment]
re-starting [build 315.3](https://travis-ci.org/UT-CHG/BET/builds/537439652) did the trick. now tests all pass.

**Comment by smattis** [comment]
Weird. Good that the version lock fixes it though. I'm going to merge.

**Comment by mathematicalmichael** [comment]
> Weird. Good that the version lock fixes it though. I'm going to merge.

I mentioned a potential way to address this in #322

**Pull request merged**
