### PR TITLE
Linting (+minor bug fix)

### PR DESCRIPTION
**Pull request by mathematicalmichael**
Re: #306

### CODE REVIEW

**Comment by smattis** [comment]
@mathematicalmichael I don't completely love this, because I think that much of the stuff that it is changing was already following PEP 8 guidelines. Surely the result does also follow PEP 8, but the changes are not necessary. We also had previously excluded the tests from linting for simplicity, but there is no reason they can't be updated. 

Also, @lcgraham and I had a policy that linting pull requests would have no other changes to the code in linting pull requests, so that they don't have to be reviewed line-by-line which can be very tedious.

**Comment by smattis** [comment]
@mathematicalmichael Is this <https://github.com/UT-CHG/BET/pull/311/commits/f24a6ce3f5fd9b91f09ed093b3e11c7f0a493d68> the only non-linting change?

**Comment by mathematicalmichael** [comment]
> @mathematicalmichael Is this [f24a6ce](https://github.com/UT-CHG/BET/commit/f24a6ce3f5fd9b91f09ed093b3e11c7f0a493d68) the only non-linting change?

yes. some travis builds failed because of this, and passed when re-run. one of the times I managed to catch it failing and track down the line number. 

Sorry, I didn't know about the policy, I only discovered it when the Travis build failed! (the nosetests were still passing for me locally). Would the correct flow have been to open a new PR from master with JUST the bug fix, wait for that to be accepted? Would that have triggered Travis to re-build this PR and see if it would work? Would I have to merge the "fixed" master into this branch with a new commit to trigger a new build # from Travis?

**Comment by mathematicalmichael** [comment]
> @mathematicalmichael I don't completely love this, because I think that much of the stuff that it is changing was already following PEP 8 guidelines. Surely the result does also follow PEP 8, but the changes are not necessary. We also had previously excluded the tests from linting for simplicity, but there is no reason they can't be updated.
> 
> Also, @lcgraham and I had a policy that linting pull requests would have no other changes to the code in linting pull requests, so that they don't have to be reviewed line-by-line which can be very tedious.

my thinking was that I kept finding places with missing spaces and wanted to fix them, but got tired of tracking them one-by-one. Lindley suggested autopep so I decided to do a pass with it. I frankly, love the changes. I think they are much more visually pleasing, and all the things I wanted to fix (inconsistency with `Test` and `test`, one-space/no-space/two-space, etc. were all handled, but I know more than that was also done.

**Comment by smattis** [comment]
@mathematicalmichael I agree that everything does look good after the linting. Just keep in mind for the future, that if you do automated linting, please do it before a new pull request, so that your submitted code is already following PEP 8, or do a separate pull request which only does linting. This makes things easy to review. It would be bad for something to get lost in the shuffle in a 2,000 line change commit.

**Pull request merged**
