### PR TITLE
Fixes errors in parallel loading of sample sets

### PR DESCRIPTION
**Pull request by lcgraham**

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
what's the status on this?

**Comment by mathematicalmichael** [comment]
I think I've gotten to the bottom of at least part of this.
in the logs, I see an attempt to reshape improperly (50 into 12x4), so this tells me the way samples per processor (or chains per) are being split up / re-combined is off.

**Comment by mathematicalmichael** [comment]
In `def test_loadmat_init()`
failure on line 70, the discretization saved has the wrong number of samples. If you want 50 but specify chain length of 5 across 3 processors, 60 samples are actually computed. This is why they cannot be re-loaded and unpacked. 

Solution is to delay `set_values` until `num_samples1` and `num_samples2` are computed, instantiate with those instead of manually setting 50 and 60.

**Comment by mathematicalmichael** [comment]
Once #355 is merged, this branch can be safely closed since I used it as a starting point for the changes that ended up in there (kind of like an informal, manual re-base).

**Comment by mathematicalmichael** [comment]
after more than two years, this is finally fixed. @lcgraham I'm closing it out. =)

**Comment by lcgraham** [comment]
Yay!!!

**Pull request closed without merging**
