### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by lcgraham**

### CODE REVIEW

**Comment by eecsu** [comment]
This looks like it undoes much of the changes to the sensitivity example documentation that I made in the recently merged pull request. Why? The old documentation was confusing. For example, linear_condnum_binratio.txt undoes basically everything I did, removes the listed steps in the process, etc. This is no longer even matching the actual example file which was updated unless those have been rolled back too. I will check.

**Comment by eecsu** [comment]
I think you want to use the sensitivity documentation I previously updated. I just checked the examples to make sure and the ones for which I updated the documentation are no longer reflected by the removal of all the changes to the documentation I made. Fix those and then I think everything is okay.

**Comment by lcgraham** [comment]
I will comment when ready.

**Comment by lcgraham** [comment]
This should be ready now.

**Comment by eecsu** [comment]
I should have read your last comment first. Checking out your branch now.

**Pull request merged**
