### PR TITLE
fixes errors in basicSampling and assoc. tests

### PR DESCRIPTION
**Pull request by lcgraham**

### CODE REVIEW

**Comment by smattis** [comment]
It looks like the CI tests are messing up when run in parallel. The plotP tests are the culprit. Did we make sure they passed before merging Troy's changes?

**Comment by lcgraham** [comment]
Troy told me that all of the plotP tests passed, but maybe he didn't check
in parallel. It might have been missed since Shippable was added after
Troy's changes.

On Thu, May 12, 2016 at 12:59 PM Steven Mattis <notifications@github.com>
wrote:

> It looks like the CI tests are messing up when run in parallel. The plotP
> tests are the culprit. Did we make sure they passed before merging Troy's
> changes?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/pull/184#issuecomment-218819941>
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by smattis** [comment]
I am ready to do my pull request for calculateP. Although, everything is not passing in parallel with this pull request, I think I might merge it, so that I can merge with it and then do my pull request. We might just have to figure out the parallel issues later. Thoughts?

Also, I likely will end up getting rid of your volume calculations in calculateP. I have added a function for sample sets that lets you define methods for calculating volumes. I'm trying to keep stuff that is hard-coded for Voronoi tesselations out of calculateP. It will make sense when you see. 

Think it's ok to merge this now?

**Comment by smattis** [comment]
I'm experimenting with using Travis instead of Shippable.

**Comment by smattis** [comment]
Why did you cancel? I spent like 20 minutes figuring out how to rerun that?

**Comment by lcgraham** [comment]
OH because I hadn't pulled the new changes you made into it. So I was
confused. I can start it again. Sorry!

On Thu, May 12, 2016 at 6:19 PM Steven Mattis <notifications@github.com>
wrote:

> Why did you cancel? I spent like 20 minutes figuring out how to rerun that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/pull/184#issuecomment-218902484>
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by lcgraham** [comment]
Sounds good. I'll have to take a look at what you do with the volume
calculations. I still want to have them somewhere in BET at least. Also
I've implemented exact calculations for 1D. Once I see what you've done wrt
volume calculations and Voronoi tesselations, I'll be able to let you know
what I think.

But yeah we're good to merge.
On Thu, May 12, 2016 at 2:49 PM Steven Mattis <notifications@github.com>
wrote:

> I am ready to do my pull request for calculateP. Although, everything is
> not passing in parallel with this pull request, I think I might merge it,
> so that I can merge with it and then do my pull request. We might just have
> to figure out the parallel issues later. Thoughts?
>
> Also, I likely will end up getting rid of your volume calculations in
> calculateP. I have added a function for sample sets that lets you define
> methods for calculating volumes. I'm trying to keep stuff that is
> hard-coded for Voronoi tesselations out of calculateP. It will make sense
> when you see.
>
> Think it's ok to merge this now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/pull/184#issuecomment-218850570>
>
-- 

Lindley Graham, Ph.D. 2015

**Comment by smattis** [comment]
I realized that you didn't actually have to pull the changes. You didn't touch .travis.yml, so there was no issue with merging or anything. No problems. I was just watching the shippable results in real time and was very confused by why it was cancelling.

**Comment by lcgraham** [comment]
@smattis I guess I'm confused because I only see the shippable happening and not the travis.

**Comment by smattis** [comment]
Ahh. You will see the travis stuff as well from now on. As far as travis knows, this pull request doesn't exist until some change is made to it because the webhook was made after any changes were made to #184

**Comment by smattis** [comment]
@lcgraham I think Shippable is freezing on the parallel tests again. So annoying. Can you just maybe add some whitespace and push so that Travis is triggered? So annoying.

**Comment by smattis** [comment]
Yay... travis is running!

**Comment by smattis** [comment]
Seems like there are maybe still some issues with tests, but I am going to merge for now.

**Comment by lcgraham** [comment]
Good call. I'm heading out of town tomorrow so I won't be able to look at the tests to see what's up till next week.

**Comment by eecsu** [comment]
What do you guys do to run the tests in parallel? I was using nosetests, but it looks like all variants I run with that just run concurrent serial tests instead of true parallel tests. All tests passed when I submitted the pull request, but it is likely they were not being truly tested in parallel.

**Comment by eecsu** [comment]
I actually am not sure that we ever had parallel postProcess tests now that I think of it. I seem to recall Steve telling me to just update the existing tests that were in test_postProcess because he was going to handle the parallel cases. I may be remembering wrong, but it just flashed in my memory that we had some brief, passing conversation about this when we were assigning the subpackage updates.

**Comment by lcgraham** [comment]
To run tests in parallel the command is 'mpirun -np nproc nosetests'

**Comment by smattis** [comment]
@eecsu It is not that we necessarily have "parallel tests," it is that we want the tests that test features that should work in parallel to run in parallel. We add exceptions for some tests that have reference data to skip when run in parallel. Just as a rule of them before doing a pull a request, you should do:
`nosetests -v`
and
`mpirun -n 2 nosetests -v`
and there should be no fails or errors. If there are, we can try to figure them out.

**Comment by eecsu** [comment]
OK. But this is what I did and I got no errors in the plotP. I ran the
linear example I was working on in flight in parallel and plots worked. How
is it failing for you?

**Comment by smattis** [comment]
Ok. I thought it was plotP because Shippable was failing when doing the plotting stuff in parallel. I think that that was actually due the build on Shippable rather than plotP. Sorry for the blame @eecsu.

There are still some issues with running new tests in parallel, though. See #189. That is assigned to @lcgraham

**Comment by lcgraham** [comment]
Yup I think that it might be somewhere in the updated sampling but I might
not have the time to check till Monday.
On Fri, May 13, 2016 at 9:55 AM Steven Mattis <notifications@github.com>
wrote:

> Ok. I thought it was plotP because Shippable was failing when doing the
> plotting stuff in parallel. I think that that was actually due the build on
> Shippable rather than plotP. Sorry for the blame @eecsu
> <https://github.com/eecsu>.
>
> There are still some issues with running new tests in parallel, though.
> See #189 <https://github.com/UT-CHG/BET/issues/189>. That is assigned to
> @lcgraham <https://github.com/lcgraham>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UT-CHG/BET/pull/184#issuecomment-219099564>
>
-- 

Lindley Graham, Ph.D. 2015

**Pull request merged**
