### PR TITLE
Remove all functions in postTools.py that have pending deprecation notices

### PR DESCRIPTION
**Pull request by User-zwj**

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
@smattis this PR was submitted a bit early. The diff should only be a single commit once #340  is merged, which @eecsu will be doing shortly. glad to know it passes checks, though!

was the removal of these deprecations done as planned? Figured 2 years later, it was an easy way to bump the coverage percentage a bit.

**Comment by smattis** [comment]
I think something needs to be changed on the branch you're trying to merge to trigger a new build. It also seems like way more is changing in this PR than just removing these functions.

**Comment by mathematicalmichael** [comment]
> I think something needs to be changed on the branch you're trying to merge to trigger a new build. It also seems like way more is changing in this PR than just removing these functions.

Yeah, this was forked off my master but submitted pre-merge so I believe the diff will become much smaller. will try to add to this PR now

**Comment by mathematicalmichael** [comment]
woo! that was my first time checking out someone's PR locally, fixing conflicts, and pushing it back. hope it works this time.

**Comment by mathematicalmichael** [comment]
... do we need to just shut this one down and try again fresh? My impression is that this should never quite be necessary to re-submit a PR. But I may be wrong.

**Comment by smattis** [comment]
I think you should just do it fresh. This branch is way too far away from master.

**Pull request closed without merging**
