### PR TITLE
gradientsRBF.py with calculate_gradients*, chooseOptQoIs, and sampling methods.

### PR DESCRIPTION
**Pull request by scottw13**
This is the up to date gradientsRBF.py subpackage.  In the end some of these methods will end up in tetsing or sampling, but for now they are here.  Removed .gitignore_global and fixed TODO syntax.

### CODE REVIEW

**Comment by lcgraham** [comment]
The .gitignore_global file needs to be removed from the repo. It should be placed somewhere convenient on your personal system like your root, home, or directory containing all of your git repositories. Repository specific git ignore files are usually .gitignore and placed in the top directory of the repository itself.

Also when leaving "to do" items for yourself, @smattis and I have been using "todo" or "TODO" for easier searching with tools like grep. If these "to do" items are in a docstring you should use the Sphinx todo directive http://sphinx-doc.org/ext/todo.html

**Comment by scottw13** [comment]
Made those changes, do I need to put in a new pull request or update this
one or has it sent you a notification automatically since I updated my fork?

Scott

**Comment by lcgraham** [comment]
There's still a .gitignore_global file in the top directory of the repo. Did you remember to commit when you removed the file? You don't need to make a new pull request the update appears in the current open pull request. When you leave a comment or reply to the e-mails for the pull request I get notified.

**Comment by scottw13** [comment]
I did commit, but I didn't do git rm, I did git add and it didnt stage that
change.  So I did git rm, the .gitignore_global is now gone.

Scott

**Pull request merged**
