### PR TITLE
V2 fixskewness

### PR DESCRIPTION
**Pull request by scottw13**
Added calculate skewness method to chooseoptQoIs module.  editted doc strings throughout. updated tests and made new tests for this new method.  updated examples to call this method rather than calcualte_avg_condnum.  lefte condnum method is just in case we want it for something later.

all tests pass on /test_sensitivity, but others tests had errors.

### CODE REVIEW

**Comment by lcgraham** [comment]
Looks good. Can you fix the following PEP8 inconsistencies and remove the unused variable? Thanks.

************* Module bet.sensitivity.gradients
C:465, 0: Line too long (81/80) (line-too-long)
C:475, 0: Line too long (87/80) (line-too-long)
C:498, 0: Line too long (84/80) (line-too-long)
C:525, 0: Line too long (86/80) (line-too-long)
C:525, 0: No space allowed before comma
    rvec = np.linalg.norm(samples[num_centers , :] - samples[num_centers + 1, :]) / 2.
                                              ^ (bad-whitespace)
C:532, 0: Line too long (166/80) (line-too-long)
C:535, 0: Line too long (117/80) (line-too-long)
C:544, 0: Line too long (155/80) (line-too-long)
C:549, 0: Line too long (182/80) (line-too-long)
C:554, 0: Exactly one space required after comma
        hessian_mat[combs[:,0], combs[:, 1]] = hessian_vec_partials[:, 0]
                           ^ (bad-whitespace)
C:555, 0: Exactly one space required after comma
        hessian_mat[combs[:,1], combs[:, 0]] = hessian_vec_partials[:, 0]
                           ^ (bad-whitespace)
C:557, 0: Line too long (81/80) (line-too-long)
************* Module bet.sensitivity.chooseQoIs
W:582, 8: Unused variable 'qois_return' (unused-variable)

**Comment by lcgraham** [comment]
Also not all of the sensitivity examples run. Could you fix this and also make sure they meet PEP8 standards?

**Comment by smattis** [comment]
A thought on the PEP8 thing: Awhile ago I thought we decided that doing any automatic PEP8 stuff should be done on it's own pull request. If you run those scripts on code it ends up making trivial modifications to SO many lines. It makes it so you can't see where the real changes to the code are. It basically makes it impossible to review a pull request without going through every line of code whether or not it was really changed.

**Comment by lcgraham** [comment]
@smattis good point about the PEP8 thing. I'd forgotten about that. I'll merge this then.

**Pull request merged**
