### PR TITLE
Localized volume emulation

### PR DESCRIPTION
**Pull request by lcgraham**
Final draft of local volume emulation (#193).  When issue #160 is completed and the attribute ``_normalized_radii`` is added to the class ``truncated_voronoi_sample_set`` (#178) then this will automatically use that value when sample specific volume emulation.

### CODE REVIEW

**Comment by lcgraham** [comment]
I need to update the docstring for estimate_local_volume since the domain is automatically scaled to the unit hyper cube. We can now handle sampling from any unit Lp ball uniformly so we might want to make this option more widely available throughout the package.

**Comment by smattis** [comment]
Are you sure this was ready to be merged? I'm not sure from the last message from @lcgraham that is was. I'll ask him.

**Comment by eecsu** [comment]
Besides needing to update the docstrings, the code looked ready. It is not in conflict with any of the existing code and only offers new functionality. There are still some features that could/will be added, but as is it looked ready to go.

**Comment by lcgraham** [comment]
I wanted the pull request to be left open so that I would remember to make those minor changes and then they would be included in this pull request. You can have multiple pull requests open at the same time without conflict.

**Comment by eecsu** [comment]
Since you called this a final draft in the pull request, I thought it was done especially since the other issues mentioned are still open, but they seemed more complimentary that issues needing to be addressed by this pull request. No?

**Comment by lcgraham** [comment]
Well I thought it was a final draft, but then I realized I had forgotten something hence my comment in the pull request. The other issues that are still open except for #

**Comment by lcgraham** [comment]
...Except for #193 which I will close momentarily.

**Pull request merged**
