### PR TITLE
rebuild documentation

### PR DESCRIPTION
**Pull request by mathematicalmichael**
had to upgrade sphinx, added assets that came with new theme package:
`pip install sphinx_rtd_theme`

these docs should include the new features of #340 ... ~~hope~~ this works.
I rebuilt the docs on `master`, then copied them over from `gh_pages/html` once I checkout out the `gh-pages` branch from upstream (`git fetch upstream`).

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
This does not include the typo fixes pending in #351 ... will use the opportunity once it is merged to show @User-zwj how to rebuild docs after making changes. Probably should also update instructions in our README to be a bit more clear. There were a lot of error messages that came up along the way that I didn't know what to do with except ignore and hope for the best. Instructions for checkout of the `gh-pages` branch after rebuilding docs, copying files, etc. would also be helpful. Perhaps we subsume these instructions into `CONTRIBUTING.md` rather than `README.md`

**Comment by mathematicalmichael** [comment]
I ran a local HTTP server to validate that the website does work. My new documentation works, hyperlinks to newly-defined types work, etc. 
should also include those instructions probably. `python -m http.server` is built-in.

**Comment by mathematicalmichael** [comment]
Screen Shot 2019-07-30 at 10 50 59 AM
only iffy thing is the bullet-item alignment.

**Comment by mathematicalmichael** [comment]
External dependencies lists `mpl_toolkits`???

**Comment by smattis** [comment]
`mpl_toolkits` is a `matplotlib` extension. I think it is needed for some plotting features.

**Comment by mathematicalmichael** [comment]
http://ut-chg.github.io/BET/overview.html#external-dependencies 
wasn't hyperlinked before either, oh well. But thanks, I suppose my computer just got that extension when I installed `matplotlib`...

**Pull request merged**
