### PR TITLE
Fixed examples to conform to new basicSampling output

### PR DESCRIPTION
**Pull request by mpilosov**
outputs are now explicitly declared.
also fixed myModel typo in linear example

### CODE REVIEW

**Comment by lcgraham** [comment]
There are a bunch of unnecessary white space changes and file mode changes in here. You also should reference the issue number in the pull request and leave that issue open until it is resolved by the pull request. There is no need to leave a dated comment in the file saying who last modified it and where since git takes care of this (see blame or blame view on github). For a small change like this I should see a handful of commits and only one file changed since the issue you were tackling was in only one file.

**Comment by mpilosov** [comment]
Sorry about that.

I just deleted and re-forked the master BET repo to get a completely clean start. Made the three small changes I needed to make
linearMapUniformSampling
nonlinearMapUniformSampling
myModel - fixed “QoI_samples = data = np.dot(parameter_samples,Q_map) “

All done in one commit only.

Then I went in and try to create a pull request and noticed the couple whitespace deletions you mentioned — I didn’t do those manually, my text editor seems to have done those automatically, but if anything, this is cleaner. I made sure not to add any comments to files.

I have zero clue what is up with file permissions (nothing I did manually. Right now I just reforked and re-installed entirely from a fresh slate) and whether or not they happened this time.

I’m going to be unavailable until the afternoon but in case what I did is correct, I hope this pull request I’m about to submit is acceptable.
I hope I got it right and the permissions didn’t change.

Best
MP
On Jun 20, 2016, at 6:13 AM, Lindley Graham <notifications@github.com<mailto:notifications@github.com>> wrote:


There are a bunch of unnecessary white space changes and file mode changes in here. You also should reference the issue number in the pull request and leave that issue open until it is resolved by the pull request. There is no need to leave a dated comment in the file saying who last modified it and where since git takes care of this (see blame or blame view on github). For a small change like this I should see a handful of commits and only one file changed since the issue you were tackling was in only one file.

**Comment by lcgraham** [comment]
Large white space changes are fine but they need to be in a separate pull request so that they don't swamp out the functional changes you are making. The same is true of large documentation changes that aren't related to the functional change you've made.

**Comment by mpilosov** [comment]
Yeah I guess I have to configure my text editor then. It wouldn't even let me have all those whitespaces at the bottom when I tried to put them back in. It autodeleted them.

So I'll make sure (next time?) to configure my changes in two stages if need be w/r/t whitespace: functional changes, and then whitespace changes, right?

Best
MP

Not sent from my computer.

On Jun 20, 2016, at 09:32, Lindley Graham <notifications@github.com<mailto:notifications@github.com>> wrote:


Large white space changes are fine but they need to be in a separate pull request so that they don't swamp out the functional changes you are making. The same is true of large documentation changes that aren't related to the functional change you've made.

-

**Comment by lcgraham** [comment]
Yup that would be great (next time). Thanks.

**Pull request closed without merging**
