### PR TITLE
Travis updated to new distribution

### PR DESCRIPTION
**Pull request by mathematicalmichael**
big changes to the file but a much better testing environment overall. Passes in 3.7 as well. 
If you'd like, we can add more experimental builds (such as nightly ones) but allow them to fail. 

Fails in 3.5. Should include in the documentation that Python 2.7+ or 3.6+ are required... 

I think we should also remove `v2_master`...

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
@lcgraham or @smattis this is ready for review (can I have my privileges back now so I can assign such roles and add labels instead of tagging y'all?)

**Comment by smattis** [comment]
@mathematicalmichael What on earth is happening here? You have just added the `.hound.yml` file, removed the `v2_master` (which is fine) from the travis file and added two new branches to the .yml file that don't exist in the main BET system. 

What exactly does hound do? What is going on here?

**Comment by smattis** [comment]
Also, can you not request me to review the pull request on the menu on the right with read access?

**Comment by smattis** [comment]
I think you messed up and reverted all of your changes or something. When you make the changes again, please give a reason why this is a better testing environment.

**Comment by mathematicalmichael** [comment]
@smattis pardon? the commits up until the `.hound` file were for travis. Hound is another CI service that automatically comments on new PRs with linting suggestions. I started using it on my fork. 
The other two branches are on my fork as well. I didn't know if you wanted them pushed to this repo or just take PRs right into master. From what I can tell, there are dev branches here. I don't know how to push/request new branches here since I don't have R/W access.

No, I cannot request anything. the whole menu is grayed out.

The travis.yml file has big changes in it that are meant to take advantage of Travis' newer distributions.

**Comment by mathematicalmichael** [comment]
@smattis oh goodness gracious! you're right, the changes to the travis file have been gone. 
okay... I'm going to try this again by submitting a PR with nothing but the new travis file in it. 
You can ignore the Hound thing for now, or check it out in use in my repo. I wasn't really sure how to use it in my repo without getting in to this one. Hound is calling Flex8. So far it's been making good suggestions. And their philosophy is to not change old code to adhere to new styles, only review new PRs, encouraging gradual adherence to cleaner code.

**Pull request closed without merging**
