### PR TITLE
Updates to the sensitivity examples

### PR DESCRIPTION
**Pull request by eecsu**
I did not update two of the linear sensitivity examples, and I think the two I left alone (linear_measure_binsize_large and linear_skewness_binratio) should probably be ignored for now. There are a lot of options set within the call to ``chooseOptQoIs_large`` that need to be motivated. Right now, I do not think they add anything to the conversation that is not captured in the big picture by the two examples I did update.

### CODE REVIEW

**Comment by lcgraham** [comment]
Looks good. @scottw13, @smattis?

**Comment by eecsu** [comment]
I should have noted that this resolves #213 and moves us from the 2.0beta to just v2.0.

**Comment by scottw13** [comment]
Looks good to me.

**Comment by smattis** [comment]
Looks good to me. Do we also want to merge #271 before releasing v2.0?

**Comment by lcgraham** [comment]
Yes, we want to merge #271 prior to release. Also as soon as everything is merged I'll handle the final touches for the release #274.

**Pull request merged**
